big_lesson/big_lesson/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


# TODO api
# Пока отключил, чтобы не заливать на боевой сервер
# router = routers.DefaultRouter()
# router.register(r'News', NewsViewSet)
# router.register(r'Client', ClientViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_app.urls', namespace='test_app')),
    path('users/', include('userapp.urls', namespace='usersr')),
    path('api/', include('rest_framework.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

big_lesson/test_app/urls.py
from django.urls import path
from . import views

app_name = 'test_app'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('prices/', views.Prices.as_view(), name='prices'),
    path('client_list/', views.ClientsListView.as_view(), name='client_list'),
    path('delivery/', views.Delivery.as_view(), name='delivery'),
    path('buy/', views.Buy.as_view(), name='buy'),
    path('check/', views.Check.as_view(), name='check'),
    path('export/', views.Export.as_view(), name='export'),
    path('contact_us/', views.ContactUs.as_view(), name='contact_us'),
    path('submit_application/', views.Application.as_view(), name='submit_application'),
    path('news01/', views.News01.as_view(), name='news01'),
    path('news02/', views.News02.as_view(), name='news02'),
    path('news03/', views.News03.as_view(), name='news03'),
    path('news-list/', views.NewsListView.as_view(), name='news_list'),
    path('create_news/', views.CreateNews.as_view(), name='create_news'),
    path('update_news/<int:pk>/', views.NewsUpdateView.as_view(), name='update_news'),
    path('create_feedback/', views.CreateFeedback.as_view(), name='create_feedback'),
    path('photos/', views.Photos.as_view(), name='photos'),
    path('client-delete/<int:pk>/', views.ClientDeleteView.as_view(), name='client_delete'),
    path('news-delete/<int:pk>/', views.NewsDeleteView.as_view(), name='news_delete')
]

big_lesson/userapp/urls.py
from django.urls import path
from userapp import views
from django.contrib.auth.views import LogoutView

app_name = 'userapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', views.UserCreateView.as_view(), name='registration'),
]

big_lesson/userapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class DeliveryUser(AbstractUser):
    email = models.EmailField(unique=True)
    is_news_maker = models.BooleanField(default=False)

big_lesson/userapp/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms

from .models import DeliveryUser


class RegistrationForm(UserCreationForm):
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', required=False,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль', required=False,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = DeliveryUser
        fields = ('username', 'password1', 'password2', 'email')


class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Имя пользователя',
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Пароль', required=False,
                               widget=forms.PasswordInput(attrs={'class': 'form-control'}))

big_lesson/userapp/views.py
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy


from .forms import RegistrationForm, LoginForm
from django.views.generic import CreateView
from .models import DeliveryUser


class UserLoginView(LoginView):
    template_name = 'userapp/login.html'
    authentication_form = LoginForm


class UserCreateView(CreateView):
    model = DeliveryUser
    template_name = 'userapp/registration.html'
    form_class = RegistrationForm
    success_url = reverse_lazy('userapp:login')

big_lesson/userapp/templates/userapp/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        {% include 'test_app/include_files/head.html' %}
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'test_app:index' %}"><img src="/media/cropped-222.png"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item"><a class="nav-link" href="{% url 'test_app:prices' %}">ПРАЙС</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">НАШИ УСЛУГИ</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'test_app:delivery' %}">Доставка в рф</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:buy' %}">Выкуп товара</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:check' %}">Проверка товара</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:export' %}">Вывоз личных вещей</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'test_app:submit_application' %}">ПОДАТЬ ЗАЯВКУ</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">ПОСЛЕДНИЕ НОВОСТИ</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    {% if news00.title %}
                                        <li><a class="dropdown-item" href="{% url 'test_app:news01' %}">{{ news00.title }}</a></li>
                                    {% endif %}
                                    {% if news01.title %}
                                        <li><a class="dropdown-item" href="{% url 'test_app:news02' %}">{{ news01.title }}</a></li>
                                    {% endif %}
                                    {% if news02.title %}
                                        <li><a class="dropdown-item" href="{% url 'test_app:news03' %}">{{ news02.title }}</a></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="{% url 'test_app:news_list' %}" style="background-color: #32393f; color: white;">все новости</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'test_app:contact_us' %}">КОНТАКТЫ</a></li>

                            {% if user.is_superuser %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">администрация</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'test_app:create_news' %}">Добавить новость</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:create_feedback' %}">Добавить отзыв</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:client_list' %}">Список клиентов</a></li>
                                </ul>
                            </li>
                            {% endif %}

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">Войти</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'userapp:login' %}">войти</a></li>
                                    {% if user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url 'userapp:logout' %}">выйти</a></li>
                                    {% else %}
                                        <li><a class="dropdown-item" href="{% url 'userapp:registration' %}">зарегистрироваться</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="">{{user.username}}</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <br>
            <br>
            <!-- Page Content-->
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <center>
                <div class="col-lg-8 col-xl-6">
                    <center>
                        <form method="post" id="contactForm">
                            {% csrf_token %}
                            {% for field in form %}
                                <p class="lead fw-normal text-muted mb-0">{{field.label_tag}}</p>
                                <p>{{field}}</p>
                                {% for error in field.errors %}
                                    {{error}}
                                {% endfor %}
                            {% endfor %}
                            <br>
                            <button class="s-button" type ="submit" id="sendMessageButton">Войти</button>
                        </form>
                    </center>
                </div>
            </center>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        <!-- Call to action-->
        {% include 'test_app/include_files/footer.html' %}
        </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

big_lesson/userapp/templates/userapp/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        {% include 'test_app/include_files/head.html' %}
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'test_app:index' %}"><img src="/media/cropped-222.png"></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item"><a class="nav-link" href="{% url 'test_app:prices' %}">ПРАЙС</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">НАШИ УСЛУГИ</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'test_app:delivery' %}">Доставка в рф</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:buy' %}">Выкуп товара</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:check' %}">Проверка товара</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:export' %}">Вывоз личных вещей</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'test_app:submit_application' %}">ПОДАТЬ ЗАЯВКУ</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">ПОСЛЕДНИЕ НОВОСТИ</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    {% if news00.title %}
                                        <li><a class="dropdown-item" href="{% url 'test_app:news01' %}">{{ news00.title }}</a></li>
                                    {% endif %}
                                    {% if news01.title %}
                                        <li><a class="dropdown-item" href="{% url 'test_app:news02' %}">{{ news01.title }}</a></li>
                                    {% endif %}
                                    {% if news02.title %}
                                        <li><a class="dropdown-item" href="{% url 'test_app:news03' %}">{{ news02.title }}</a></li>
                                    {% endif %}
                                    <li><a class="dropdown-item" href="{% url 'test_app:news_list' %}" style="background-color: #32393f; color: white;">все новости</a></li>
                                </ul>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'test_app:contact_us' %}">КОНТАКТЫ</a></li>

                            {% if user.is_superuser %}
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">администрация</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'test_app:create_news' %}">Добавить новость</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:create_feedback' %}">Добавить отзыв</a></li>
                                    <li><a class="dropdown-item" href="{% url 'test_app:client_list' %}">Список клиентов</a></li>
                                </ul>
                            </li>
                            {% endif %}

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">Войти</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                                    <li><a class="dropdown-item" href="{% url 'userapp:login' %}">войти</a></li>
                                    {% if user.is_authenticated %}
                                        <li><a class="dropdown-item" href="{% url 'userapp:logout' %}">выйти</a></li>
                                    {% else %}
                                        <li><a class="dropdown-item" href="{% url 'userapp:registration' %}">зарегистрироваться</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="">{{user.username}}</a></li>
                        </ul>
                    </div>
                </div>
            </nav>
            <br>
            <br>
            <!-- Page Content-->
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <center>
                <div class="col-lg-8 col-xl-6">
                    <center>
                        <form method="post" id="contactForm">
                            {% csrf_token %}
                            {% for field in form %}
                                <p class="lead fw-normal text-muted mb-0">{{field.label_tag}}</p>
                                <p>{{field}}</p>
                                {% for error in field.errors %}
                                    {{error}}
                                {% endfor %}
                            {% endfor %}
                            <br>
                            <button class="s-button" type ="submit" id="sendMessageButton">Зарегистрироваться</button>
                        </form>
                    </center>
                </div>
            </center>
            <br>
            <br>
            <br>
        <!-- Call to action-->
        {% include 'test_app/include_files/footer.html' %}
        </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>