big_lesson/big_lesson/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


# TODO api
# Пока отключил, чтобы не заливать на боевой сервер
# router = routers.DefaultRouter()
# router.register(r'News', NewsViewSet)
# router.register(r'Client', ClientViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_app.urls', namespace='test_app')),
    path('users/', include('userapp.urls', namespace='usersr')),
    path('api/', include('rest_framework.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

big_lesson/test_app/urls.py
from django.urls import path
from . import views

app_name = 'test_app'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('prices/', views.Prices.as_view(), name='prices'),
    path('client_list/', views.ClientsListView.as_view(), name='client_list'),
    path('delivery/', views.Delivery.as_view(), name='delivery'),
    path('buy/', views.Buy.as_view(), name='buy'),
    path('check/', views.Check.as_view(), name='check'),
    path('export/', views.Export.as_view(), name='export'),
    path('contact_us/', views.ContactUs.as_view(), name='contact_us'),
    path('submit_application/', views.Application.as_view(), name='submit_application'),
    path('news01/', views.News01.as_view(), name='news01'),
    path('news02/', views.News02.as_view(), name='news02'),
    path('news03/', views.News03.as_view(), name='news03'),
    path('news-list/', views.NewsListView.as_view(), name='news_list'),
    path('create_news/', views.CreateNews.as_view(), name='create_news'),
    path('update_news/<int:pk>/', views.NewsUpdateView.as_view(), name='update_news'),
    path('create_feedback/', views.CreateFeedback.as_view(), name='create_feedback'),
    path('photos/', views.Photos.as_view(), name='photos'),
    path('client-delete/<int:pk>/', views.ClientDeleteView.as_view(), name='client_delete'),
    path('news-delete/<int:pk>/', views.NewsDeleteView.as_view(), name='news_delete')
]

big_lesson/userapp/urls.py
from django.urls import path
from userapp import views
from django.contrib.auth.views import LogoutView

app_name = 'userapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', views.UserCreateView.as_view(), name='registration'),
]

big_lesson/test_app/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Client(models.Model):

    description = models.CharField(null=True, max_length=1012, verbose_name='Описание')
    link = models.CharField(max_length=1012, blank=True, null=True, verbose_name='Ссылка')
    color = models.CharField(max_length=64, unique=False, null=True, verbose_name='Цвет')
    amount = models.CharField(null=True, max_length=64, verbose_name='Кол-во')
    price = models.CharField(null=True, max_length=64, verbose_name='Цента за шт.')
    name = models.CharField(null=True, max_length=64, verbose_name='Ваше имя')
    phone_number = models.CharField(null=True, max_length=64, verbose_name='Ваш номер телефона')
    create = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.name}, {self.phone_number}'


class News(models.Model):
    title = models.CharField(max_length=100, unique=True, null=True)
    text = models.TextField(null=True)
    video_link = models.CharField(max_length=1000, blank=True, null=True)
    img1 = models.FileField(upload_to='clients', null=True, blank=True)
    img2 = models.FileField(upload_to='clients', null=True, blank=True)
    img3 = models.FileField(upload_to='clients', null=True, blank=True)
    img4 = models.FileField(upload_to='clients', null=True, blank=True)
    img5 = models.FileField(upload_to='clients', null=True, blank=True)
    create = models.DateTimeField(default=timezone.now)

    def has_image(self):
        return bool(self.img1)

    def __str__(self):
        return f'{self.title}'


class Feedback(models.Model):
    name = models.CharField(max_length=32, unique=False)
    img = models.FileField(upload_to='clients', null=True, blank=True)
    link = models.CharField(max_length=32, unique=False)

    def __str__(self):
        return self.name


class Imgs(models.Model):
    name = models.CharField(max_length=32, unique=False)
    img1 = models.FileField(upload_to='clients', null=True, blank=True)
    img2 = models.FileField(upload_to='clients', null=True, blank=True)
    img3 = models.FileField(upload_to='clients', null=True, blank=True)

    def __str__(self):
        return self.name

big_lesson/test_app/forms.py
from django import forms


class UploadFileForm(forms.Form):
    name = forms.CharField(max_length=32, unique=True)
    img = forms.FileField(upload_to='clients', null=True, blank=True)
    link = forms.URLField()


class NewsForm(forms.Form):
    title = forms.CharField(max_length=32, unique=True)
    text = forms.CharField(max_length=32, unique=True)
    video_link = forms.CharField(max_length=32, unique=False)
    img1 = forms.FileField(upload_to='clients', null=True, blank=True)
    img2 = forms.FileField(upload_to='clients', null=True, blank=True)
    img3 = forms.FileField(upload_to='clients', null=True, blank=True)
    img4 = forms.FileField(upload_to='clients', null=True, blank=True)
    img5 = forms.FileField(upload_to='clients', null=True, blank=True)

# class ContactForm(forms.Form):
#     name = forms.CharField(label='имя')
#     email = forms.EmailField(label='email')
#     phone_number = forms.CharField(label='номер телефона')
#
#
# class NewsForm(forms.Form):
#     title = forms.CharField(label='Название новости', max_length=100)
#     text = forms.CharField(widget=forms.Textarea)
#     video_link = forms.CharField(label='Ссылка на видео', widget=forms.TextInput(
#         attrs={'placeholder': 'https://www.youtube.com/embed/id', 'class': 'form-control'}))

big_lesson/test_app/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView, DeleteView, UpdateView
from django.db.models.signals import pre_save
from django.dispatch import receiver

from .models import Client, News, Feedback, Imgs
from django.views.generic.base import ContextMixin

'''
в каждой вьюшке происходит проверка на кол-во новостей, в зависимости от этого
рендерится страница
'''


# Главная страница
def main_view(request):
    feedback = Feedback.objects.all()
    news = News.objects.order_by('-id')
    photos = Imgs.objects.order_by('-id')
    photos00 = photos[0]
    if len(news) == 0:
        return render(request, 'test_app/index.html', context={'feedback': feedback, 'photos00': photos00})
    if len(news) == 1:
        news00 = news[0]
        return render(request, 'test_app/index.html',
                      context={'feedback': feedback, 'photos00': photos00, 'news00': news00})
    elif len(news) == 2:
        news00 = news[0]
        news01 = news[1]
        return render(request, 'test_app/index.html',
                      context={'feedback': feedback, 'photos00': photos00, 'news00': news00, 'news01': news01})
    elif len(news) >= 3:
        news00 = news[0]
        news01 = news[1]
        news02 = news[2]
        return render(request, 'test_app/index.html',
                      context={'feedback': feedback, 'photos00': photos00, 'news00': news00, 'news01': news01,
                               'news02': news02})


# Класс для множественного наследования.
# Добавляем контекст для всех страниц.
class NewsContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        """
        context = super().get_context_data(**kwargs)
        news = News.objects.order_by('-id')
        if len(news) == 0:
            return context
        elif len(news) == 1:
            news00 = news[0]
            context['news00'] = news00
            return context
        elif len(news) == 2:
            news00 = news[0]
            context['news00'] = news00
            news01 = news[1]
            context['news01'] = news01
            return context
        elif len(news) >= 3:
            news00 = news[0]
            context['news00'] = news00
            news01 = news[1]
            context['news01'] = news01
            news02 = news[2]
            context['news02'] = news02
            return context


# Цены
class Prices(TemplateView, NewsContextMixin):
    template_name = 'test_app/prices.html'


# Наши услуги. 4 вкладки
class Delivery(TemplateView, NewsContextMixin):
    template_name = 'test_app/delivery.html'


class Buy(TemplateView, NewsContextMixin):
    template_name = 'test_app/buy.html'


class Check(TemplateView, NewsContextMixin):
    template_name = 'test_app/check.html'


class Export(TemplateView, NewsContextMixin):
    template_name = 'test_app/export.html'


class Application(CreateView, NewsContextMixin):
    fields = ['description', 'link', 'color', 'amount', 'price', 'name', 'phone_number']
    model = Client
    success_url = reverse_lazy('test_app:index')
    template_name = 'test_app/submit_application.html'


'''
!!!!!!
'''


# TODO  1
class CreateFeedback(UserPassesTestMixin, CreateView, NewsContextMixin):
    fields = ['name', 'link', 'img']
    model = Feedback
    success_url = reverse_lazy('test_app:index')
    template_name = 'test_app/create_feedback.html'

    def test_func(self):
        return self.request.user.is_superuser


class Photos(UserPassesTestMixin, CreateView, NewsContextMixin):
    fields = ['name', 'img1', 'img2', 'img3']
    model = Imgs
    success_url = reverse_lazy('test_app:index')
    template_name = 'test_app/photos.html'

    def test_func(self):
        return self.request.user.is_superuser


class CreateNews(UserPassesTestMixin, CreateView, NewsContextMixin):
    fields = ['title', 'video_link', 'text', 'img1', 'img2', 'img3', 'img4', 'img5']
    model = News
    success_url = reverse_lazy('test_app:news01')
    template_name = 'test_app/create_news.html'

    def test_func(self):
        return self.request.user.is_superuser

    @receiver(pre_save, sender=News)
    def change_video_link(sender, instance, **kwargs):

        if not instance.video_link:
            return

        # получить video_link из формы
        video_link = instance.video_link
        # изменить video_link по вашему усмотрению
        video_link = video_link.replace("watch?v=", "embed/")
        # найти индекс символа "&"
        try:
            index = video_link.index("&")
            # сделать срез строки до индекса
            video_link = video_link[:index]
        except ValueError:
            # если символ "&" не найден, то ничего не делать
            pass
        # сохранить измененный video_link в экземпляре модели
        instance.video_link = video_link


class ContactUs(TemplateView, NewsContextMixin):
    template_name = 'test_app/contact_us.html'


'''
!!!!!!!!!!!!!!!!!! Блок с новостями !!!!!!!!!!!!!!!!!!
'''


class News01(TemplateView, NewsContextMixin):
    template_name = 'test_app/news_01.html'


class News02(TemplateView, NewsContextMixin):
    template_name = 'test_app/news_02.html'


class News03(TemplateView, NewsContextMixin):
    template_name = 'test_app/news_03.html'


class NewsListView(ListView, NewsContextMixin):
    model = News
    template_name = 'test_app/news_list.html'
    paginate_by = 2
    title = 'Новости'

    def get_queryset(self):
        return super(NewsListView, self).get_queryset().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class ClientsListView(UserPassesTestMixin, ListView, NewsContextMixin):
    model = Client
    template_name = 'test_app/client_list.html'

    def get_queryset(self):
        return super(ClientsListView, self).get_queryset().order_by('-id')

    def test_func(self):
        return self.request.user.is_superuser


class ClientDeleteView(DeleteView, NewsContextMixin):
    template_name = 'test_app/client_delete_confirm.html'
    model = Client
    success_url = reverse_lazy('test_app:client_list')


class NewsDeleteView(DeleteView, NewsContextMixin):
    template_name = 'test_app/news_delete_confirm.html'
    model = News
    success_url = reverse_lazy('test_app:news_list')


class NewsUpdateView(UpdateView, NewsContextMixin):
    fields = ['title', 'video_link', 'text', 'img1', 'img2', 'img3', 'img4', 'img5']
    model = News
    success_url = reverse_lazy('test_app:news_list')
    template_name = 'test_app/create_news.html'

big_lesson/test_app/templates/test_app/client_delete_confirm.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'test_app/include_files/head.html' %}
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <a class="navbar-brand" href="{% url 'test_app:index' %}"><img src="/media/cropped-222.png"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'test_app:prices' %}">ПРАЙС</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">НАШИ УСЛУГИ</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            <li><a class="dropdown-item" href="{% url 'test_app:delivery' %}">Доставка в рф</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:buy' %}">Выкуп товара</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:check' %}">Проверка товара</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:export' %}">Вывоз личных вещей</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'test_app:submit_application' %}">ПОДАТЬ ЗАЯВКУ</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">ПОСЛЕДНИЕ НОВОСТИ</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            {% if news00.title %}
                                <li><a class="dropdown-item" href="{% url 'test_app:news01' %}">{{ news00.title }}</a></li>
                            {% endif %}
                            {% if news01.title %}
                                <li><a class="dropdown-item" href="{% url 'test_app:news02' %}">{{ news01.title }}</a></li>
                            {% endif %}
                            {% if news02.title %}
                                <li><a class="dropdown-item" href="{% url 'test_app:news03' %}">{{ news02.title }}</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'test_app:news_list' %}" style="background-color: #32393f; color: white;">все новости</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'test_app:contact_us' %}">КОНТАКТЫ</a></li>

                    {% if user.is_superuser %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">администрация</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            <li><a class="dropdown-item" href="{% url 'test_app:create_news' %}">Добавить новость</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:create_feedback' %}">Добавить отзыв</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:client_list' %}">Список клиентов</a></li>
                        </ul>
                    </li>
                    {% endif %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">Войти</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            <li><a class="dropdown-item" href="{% url 'userapp:login' %}">войти</a></li>
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'userapp:logout' %}">выйти</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'userapp:registration' %}">зарегистрироваться</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="">{{user.username}}</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <center>
        <h1 class="fw-bolder">Удалить клиента {{object.name}}</h1>
        <br>
        <hr>
        <br>
        <h3 style="color: #404147">Вы уверены?</h3>
        <br>
        <br>
        <form method="post">
            {% csrf_token %}
            <button class="d-button" type="submit">Да</button>
            <a href="{% url 'test_app:client_list' %}">
                <button class="n-button" type="button">Отмена</button>
            </a>
        </form>
    </center>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <!-- Call to action-->
    {% include 'test_app/include_files/footer.html' %}
</body>
</html>

big_lesson/test_app/templates/test_app/news_delete_confirm.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'test_app/include_files/head.html' %}
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <a class="navbar-brand" href="{% url 'test_app:index' %}"><img src="/media/cropped-222.png"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><a class="nav-link" href="{% url 'test_app:prices' %}">ПРАЙС</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">НАШИ УСЛУГИ</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            <li><a class="dropdown-item" href="{% url 'test_app:delivery' %}">Доставка в рф</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:buy' %}">Выкуп товара</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:check' %}">Проверка товара</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:export' %}">Вывоз личных вещей</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'test_app:submit_application' %}">ПОДАТЬ ЗАЯВКУ</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">ПОСЛЕДНИЕ НОВОСТИ</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            {% if news00.title %}
                                <li><a class="dropdown-item" href="{% url 'test_app:news01' %}">{{ news00.title }}</a></li>
                            {% endif %}
                            {% if news01.title %}
                                <li><a class="dropdown-item" href="{% url 'test_app:news02' %}">{{ news01.title }}</a></li>
                            {% endif %}
                            {% if news02.title %}
                                <li><a class="dropdown-item" href="{% url 'test_app:news03' %}">{{ news02.title }}</a></li>
                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'test_app:news_list' %}" style="background-color: #32393f; color: white;">все новости</a></li>
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'test_app:contact_us' %}">КОНТАКТЫ</a></li>

                    {% if user.is_superuser %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">администрация</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            <li><a class="dropdown-item" href="{% url 'test_app:create_news' %}">Добавить новость</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:create_feedback' %}">Добавить отзыв</a></li>
                            <li><a class="dropdown-item" href="{% url 'test_app:client_list' %}">Список клиентов</a></li>
                        </ul>
                    </li>
                    {% endif %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">Войти</a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                            <li><a class="dropdown-item" href="{% url 'userapp:login' %}">войти</a></li>
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'userapp:logout' %}">выйти</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'userapp:registration' %}">зарегистрироваться</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="">{{user.username}}</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <center>
        <h1 class="fw-bolder">Удалить новость "{{object.title}}"</h1>
        <br>
        <hr>
        <br>
        <h3 style="color: #404147">Вы уверены?</h3>
        <br>
        <br>
        <form method="post">
            {% csrf_token %}
            <button class="d-button" type="submit">Да</button>
            <a href="{% url 'test_app:news_list' %}">
                <button class="n-button" type="button">Отмена</button>
            </a>
        </form>
    </center>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <!-- Call to action-->
    {% include 'test_app/include_files/footer.html' %}
</body>
</html>

big_lesson/test_app/templates/test_app/news_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        {% include 'test_app/include_files/head.html' %}
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            {% include 'test_app/include_files/navigation.html' %}
            <!-- Page Content-->
            <section class="py-5">
                <br>
                <br>
                <br>
                <div class="text-center mb-5">
                    <h1 class="fw-bolder">{{title}}</h1>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
                    <script>
                    jQuery(document).ready(function($) {
                      $('.spoiler_title').click(function() {
                         $(this).parents('.spoiler_wrap').find('.spoiler_content').toggleClass('open');
                             $(this).parents('.spoiler_wrap').find('.spoiler_arrow').toggleClass('open');
                      });
                    });
                    </script>
                    {% for item in object_list %}
                    {% if item.title %}
                        <div class="spoiler_wrap">
                            <div class="spoiler_title"><h2>{{ item.title }}</h2>
                                <span class="spoiler_arrow"><svg viewBox="-122.9 121.1 105.9 61.9"><path d="M-63.2 180.3l43.5-43.5c1.7-1.7 2.7-4 2.7-6.5s-1-4.8-2.7-6.5c-1.7-1.7-4-2.7-6.5-2.7s-4.8 1-6.5 2.7L-69.9 161l-37.2-37.2c-1.7-1.7-4-2.7-6.5-2.7s-4.8 1-6.5 2.6c-1.9 1.8-2.8 4.2-2.8 6.6 0 2.3.9 4.6 2.6 6.5 11.4 11.5 41 41.2 43 43.3l.2.2c3.6 3.6 10.3 3.6 13.9 0z"></path></svg></span>
                            </div>
                            <div class="spoiler_content">
                                {% if user.is_superuser %}
                                    <a href="{% url 'test_app:news_delete' pk=item.pk %}">
                                        <button class="d-button" type="button">Удалить</button>
                                    </a>
                                    <a href="{% url 'test_app:update_news' pk=item.pk %}">
                                        <button class="n-button" type="button">Изменить</button>
                                    </a>
                                {% endif %}
                                <p class="lead fw-normal text-muted">{{ item.text|linebreaks }}</p>
                                {% if item.video_link %}
                                <center>
                                    <div class="container-fluid">
                                        <iframe src={{ item.video_link }}></iframe>
                                    </div>
                                </center>
                                {% endif %}
                                <p class="lead fw-normal text-muted">{{ item.create }}</p>

                            </div>
                        </div>
                    {% endif %}
                    {% endfor %}


                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="/news-list?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="/news-list?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}

                </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            </section>
        </main>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <!-- Call to action-->
        {% include 'test_app/include_files/footer.html' %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>