big_lesson/big_lesson/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


# TODO api
# Пока отключил, чтобы не заливать на боевой сервер
# router = routers.DefaultRouter()
# router.register(r'News', NewsViewSet)
# router.register(r'Client', ClientViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_app.urls', namespace='test_app')),
    path('users/', include('userapp.urls', namespace='usersr')),
    path('api/', include('rest_framework.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

big_lesson/test_app/urls.py
from django.urls import path
from . import views

app_name = 'test_app'

urlpatterns = [
    path('', views.main_view, name='index'),
    path('prices/', views.Prices.as_view(), name='prices'),
    path('client_list/', views.ClientsListView.as_view(), name='client_list'),
    path('delivery/', views.Delivery.as_view(), name='delivery'),
    path('buy/', views.Buy.as_view(), name='buy'),
    path('check/', views.Check.as_view(), name='check'),
    path('export/', views.Export.as_view(), name='export'),
    path('contact_us/', views.ContactUs.as_view(), name='contact_us'),
    path('submit_application/', views.Application.as_view(), name='submit_application'),
    path('news01/', views.News01.as_view(), name='news01'),
    path('news02/', views.News02.as_view(), name='news02'),
    path('news03/', views.News03.as_view(), name='news03'),
    path('news-list/', views.NewsListView.as_view(), name='news_list'),
    path('create_news/', views.CreateNews.as_view(), name='create_news'),
    path('update_news/<int:pk>/', views.NewsUpdateView.as_view(), name='update_news'),
    path('create_feedback/', views.CreateFeedback.as_view(), name='create_feedback'),
    path('photos/', views.Photos.as_view(), name='photos'),
    path('client-delete/<int:pk>/', views.ClientDeleteView.as_view(), name='client_delete'),
    path('news-delete/<int:pk>/', views.NewsDeleteView.as_view(), name='news_delete')
]

big_lesson/userapp/urls.py
from django.urls import path
from userapp import views
from django.contrib.auth.views import LogoutView

app_name = 'userapp'

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('registration/', views.UserCreateView.as_view(), name='registration'),
]

big_lesson/test_app/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Client(models.Model):

    description = models.CharField(null=True, max_length=1012, verbose_name='Описание')
    link = models.CharField(max_length=1012, blank=True, null=True, verbose_name='Ссылка')
    color = models.CharField(max_length=64, unique=False, null=True, verbose_name='Цвет')
    amount = models.CharField(null=True, max_length=64, verbose_name='Кол-во')
    price = models.CharField(null=True, max_length=64, verbose_name='Цента за шт.')
    name = models.CharField(null=True, max_length=64, verbose_name='Ваше имя')
    phone_number = models.CharField(null=True, max_length=64, verbose_name='Ваш номер телефона')
    create = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.name}, {self.phone_number}'


class News(models.Model):
    title = models.CharField(max_length=100, unique=True, null=True)
    text = models.TextField(null=True)
    video_link = models.CharField(max_length=1000, blank=True, null=True)
    img1 = models.FileField(upload_to='clients', null=True, blank=True)
    img2 = models.FileField(upload_to='clients', null=True, blank=True)
    img3 = models.FileField(upload_to='clients', null=True, blank=True)
    img4 = models.FileField(upload_to='clients', null=True, blank=True)
    img5 = models.FileField(upload_to='clients', null=True, blank=True)
    create = models.DateTimeField(default=timezone.now)

    def has_image(self):
        return bool(self.img1)

    def __str__(self):
        return f'{self.title}'


class Feedback(models.Model):
    name = models.CharField(max_length=32, unique=False)
    img = models.FileField(upload_to='clients', null=True, blank=True)
    link = models.CharField(max_length=32, unique=False)

    def __str__(self):
        return self.name


class Imgs(models.Model):
    name = models.CharField(max_length=32, unique=False)
    img1 = models.FileField(upload_to='clients', null=True, blank=True)
    img2 = models.FileField(upload_to='clients', null=True, blank=True)
    img3 = models.FileField(upload_to='clients', null=True, blank=True)

    def __str__(self):
        return self.name

big_lesson/test_app/forms.py
from django import forms


class UploadFileForm(forms.Form):
    name = forms.CharField(max_length=32, unique=True)
    img = forms.FileField(upload_to='clients', null=True, blank=True)
    link = forms.URLField()


class NewsForm(forms.Form):
    title = forms.CharField(max_length=32, unique=True)
    text = forms.CharField(max_length=32, unique=True)
    video_link = forms.CharField(max_length=32, unique=False)
    img1 = forms.FileField(upload_to='clients', null=True, blank=True)
    img2 = forms.FileField(upload_to='clients', null=True, blank=True)
    img3 = forms.FileField(upload_to='clients', null=True, blank=True)
    img4 = forms.FileField(upload_to='clients', null=True, blank=True)
    img5 = forms.FileField(upload_to='clients', null=True, blank=True)

# class ContactForm(forms.Form):
#     name = forms.CharField(label='имя')
#     email = forms.EmailField(label='email')
#     phone_number = forms.CharField(label='номер телефона')
#
#
# class NewsForm(forms.Form):
#     title = forms.CharField(label='Название новости', max_length=100)
#     text = forms.CharField(widget=forms.Textarea)
#     video_link = forms.CharField(label='Ссылка на видео', widget=forms.TextInput(
#         attrs={'placeholder': 'https://www.youtube.com/embed/id', 'class': 'form-control'}))

big_lesson/test_app/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView, DeleteView, UpdateView
from django.db.models.signals import pre_save
from django.dispatch import receiver

from .models import Client, News, Feedback, Imgs
from django.views.generic.base import ContextMixin

'''
в каждой вьюшке происходит проверка на кол-во новостей, в зависимости от этого
рендерится страница
'''


# Главная страница
def main_view(request):
    feedback = Feedback.objects.all()
    news = News.objects.order_by('-id')
    photos = Imgs.objects.order_by('-id')
    photos00 = photos[0]
    if len(news) == 0:
        return render(request, 'test_app/index.html', context={'feedback': feedback, 'photos00': photos00})
    if len(news) == 1:
        news00 = news[0]
        return render(request, 'test_app/index.html',
                      context={'feedback': feedback, 'photos00': photos00, 'news00': news00})
    elif len(news) == 2:
        news00 = news[0]
        news01 = news[1]
        return render(request, 'test_app/index.html',
                      context={'feedback': feedback, 'photos00': photos00, 'news00': news00, 'news01': news01})
    elif len(news) >= 3:
        news00 = news[0]
        news01 = news[1]
        news02 = news[2]
        return render(request, 'test_app/index.html',
                      context={'feedback': feedback, 'photos00': photos00, 'news00': news00, 'news01': news01,
                               'news02': news02})


# Класс для множественного наследования.
# Добавляем контекст для всех страниц.
class NewsContextMixin(ContextMixin):

    def get_context_data(self, *args, **kwargs):
        """
        Отвечает за передачу параметров в контекст
        """
        context = super().get_context_data(**kwargs)
        news = News.objects.order_by('-id')
        if len(news) == 0:
            return context
        elif len(news) == 1:
            news00 = news[0]
            context['news00'] = news00
            return context
        elif len(news) == 2:
            news00 = news[0]
            context['news00'] = news00
            news01 = news[1]
            context['news01'] = news01
            return context
        elif len(news) >= 3:
            news00 = news[0]
            context['news00'] = news00
            news01 = news[1]
            context['news01'] = news01
            news02 = news[2]
            context['news02'] = news02
            return context


# Цены
class Prices(TemplateView, NewsContextMixin):
    template_name = 'test_app/prices.html'


# Наши услуги. 4 вкладки
class Delivery(TemplateView, NewsContextMixin):
    template_name = 'test_app/delivery.html'


class Buy(TemplateView, NewsContextMixin):
    template_name = 'test_app/buy.html'


class Check(TemplateView, NewsContextMixin):
    template_name = 'test_app/check.html'


class Export(TemplateView, NewsContextMixin):
    template_name = 'test_app/export.html'


class Application(CreateView, NewsContextMixin):
    fields = ['description', 'link', 'color', 'amount', 'price', 'name', 'phone_number']
    model = Client
    success_url = reverse_lazy('test_app:index')
    template_name = 'test_app/submit_application.html'


'''
!!!!!!
'''


# TODO  1
class CreateFeedback(UserPassesTestMixin, CreateView, NewsContextMixin):
    fields = ['name', 'link', 'img']
    model = Feedback
    success_url = reverse_lazy('test_app:index')
    template_name = 'test_app/create_feedback.html'

    def test_func(self):
        return self.request.user.is_superuser


class Photos(UserPassesTestMixin, CreateView, NewsContextMixin):
    fields = ['name', 'img1', 'img2', 'img3']
    model = Imgs
    success_url = reverse_lazy('test_app:index')
    template_name = 'test_app/photos.html'

    def test_func(self):
        return self.request.user.is_superuser


class CreateNews(UserPassesTestMixin, CreateView, NewsContextMixin):
    fields = ['title', 'video_link', 'text', 'img1', 'img2', 'img3', 'img4', 'img5']
    model = News
    success_url = reverse_lazy('test_app:news01')
    template_name = 'test_app/create_news.html'

    def test_func(self):
        return self.request.user.is_superuser

    @receiver(pre_save, sender=News)
    def change_video_link(sender, instance, **kwargs):

        if not instance.video_link:
            return

        # получить video_link из формы
        video_link = instance.video_link
        # изменить video_link по вашему усмотрению
        video_link = video_link.replace("watch?v=", "embed/")
        # найти индекс символа "&"
        try:
            index = video_link.index("&")
            # сделать срез строки до индекса
            video_link = video_link[:index]
        except ValueError:
            # если символ "&" не найден, то ничего не делать
            pass
        # сохранить измененный video_link в экземпляре модели
        instance.video_link = video_link


class ContactUs(TemplateView, NewsContextMixin):
    template_name = 'test_app/contact_us.html'


'''
!!!!!!!!!!!!!!!!!! Блок с новостями !!!!!!!!!!!!!!!!!!
'''


class News01(TemplateView, NewsContextMixin):
    template_name = 'test_app/news_01.html'


class News02(TemplateView, NewsContextMixin):
    template_name = 'test_app/news_02.html'


class News03(TemplateView, NewsContextMixin):
    template_name = 'test_app/news_03.html'


class NewsListView(ListView, NewsContextMixin):
    model = News
    template_name = 'test_app/news_list.html'
    paginate_by = 2
    title = 'Новости'

    def get_queryset(self):
        return super(NewsListView, self).get_queryset().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.title
        return context


class ClientsListView(UserPassesTestMixin, ListView, NewsContextMixin):
    model = Client
    template_name = 'test_app/client_list.html'

    def get_queryset(self):
        return super(ClientsListView, self).get_queryset().order_by('-id')

    def test_func(self):
        return self.request.user.is_superuser


class ClientDeleteView(DeleteView, NewsContextMixin):
    template_name = 'test_app/client_delete_confirm.html'
    model = Client
    success_url = reverse_lazy('test_app:client_list')


class NewsDeleteView(DeleteView, NewsContextMixin):
    template_name = 'test_app/news_delete_confirm.html'
    model = News
    success_url = reverse_lazy('test_app:news_list')


class NewsUpdateView(UpdateView, NewsContextMixin):
    fields = ['title', 'video_link', 'text', 'img1', 'img2', 'img3', 'img4', 'img5']
    model = News
    success_url = reverse_lazy('test_app:news_list')
    template_name = 'test_app/create_news.html'

big_lesson/test_app/templates/test_app/include_files/footer.html
<aside class="bg-primary rounded-3 p-4 p-sm-5 mt-5">
    <div class="d-flex align-items-center justify-content-between flex-column flex-xl-row text-center text-xl-start">
        <div class="mb-4 mb-xl-0">
            <div class="fs-3 fw-bold text-white">Мы — Ваши руки и глаза в Китае!</div>
            <div class="text-white-50">Честность и открытость с клиентами — наш девиз! Мы всегда на связи и рады ответить на все Ваши вопросы!</div>
        </div>
        <div class="ms-xl-4">
            <div class="">
                <button onclick="topFunction()" class="btn btn-outline-light" title="Go to top">Наверх</button>
                <script>
                    // Когда пользователь прокручивает вниз 20px от верхней части документа, показать кнопку
                    window.onscroll = function() {scrollFunction()};

                    function scrollFunction() {
                      if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                        document.getElementById("myBtn").style.display = "block";
                      } else {
                        document.getElementById("myBtn").style.display = "none";
                      }
                    }

                    // Когда пользователь нажимает на кнопку, прокрутите до верхней части документа
                    function topFunction() {
                      document.body.scrollTop = 0;
                      document.documentElement.scrollTop = 0;
                    }
                </script>
            </div>
            <a class="uldinium" href="https://t.me/Uldinium">Создание сайта - Uldinium</a>
        </div>
    </div>

    <br>
    <br>
    <div class="div-big">
        <div class="div-left">
            <p class="fs-3 fw-bold text-white">WhatsApp</p>
            <p class="text-white-50">+7 922 112 08 83, Владимир</p>
            <p class="text-white-50">+7 904 169 10 43, Татьяна</p>

            <p class="fs-3 fw-bold text-white">Номер телефона в Китае</p>
            <p class="text-white-50">+86 199 2475 5375, Владимир</p>
            <p class="text-white-50">+86 180 2622 2174, Татьяна</p>
        </div>
        <div class="div-right">
            <p class="fs-3 fw-bold text-white">Мы в ВК</p>
            <a href="https://vk.com/rassvet_china" class="text-white-50">rassvet_china</a>

            <p class="fs-3 fw-bold text-white">Мы в инстаграм</p>
            <p class="text-white-50">rassvet_china</p>

            <p class="fs-3 fw-bold text-white">WeChatID</p>
            <p class="text-white-50">Kiselev-Vlad</p>
        </div>
    </div>
</aside>

<div id='follow'>
    <a href="https://wa.me/79221120883" target='_blank'>
    <img class="img1" src="/media/whatsapp.png" alt=""/></a>
</div>

big_lesson/test_app/templates/test_app/include_files/head.html
{% load static %}

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
<meta name="description" content="" />
<meta name="author" content="" />
<title>Рассвет</title>
<!-- Favicon-->
<link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.png' %}" />
<!-- Bootstrap icons-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
<!-- Core theme CSS (includes Bootstrap)-->
<link href="{% static 'css/styles.css' %}" rel="stylesheet" />
<script src="{% static 'js/scripts.js' %}"></script>

big_lesson/test_app/templates/test_app/include_files/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-opacity-100">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'test_app:index' %}"><img src="../media/cropped-222.png"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'test_app:prices' %}">ЦЕНЫ</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">НАШИ УСЛУГИ</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                        <li><a class="dropdown-item" href="{% url 'test_app:buy' %}">выкуп товара</a></li>
                        <li><a class="dropdown-item" href="{% url 'test_app:check' %}">проверка товара</a></li>
                        <li><a class="dropdown-item" href="{% url 'test_app:delivery' %}">доставка в Россию и Казахстан</a></li>
                        <li><a class="dropdown-item" href="{% url 'test_app:export' %}">оплата продавцам и перевод денег в Китай</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'test_app:submit_application' %}">ПОДАТЬ ЗАЯВКУ</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">ПОСЛЕДНИЕ НОВОСТИ</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                        {% if news00.title %}
                            <li><a class="dropdown-item" href="{% url 'test_app:news01' %}">{{ news00.title }}</a></li>
                        {% endif %}
                        {% if news01.title %}
                            <li><a class="dropdown-item" href="{% url 'test_app:news02' %}">{{ news01.title }}</a></li>
                        {% endif %}
                        {% if news02.title %}
                            <li><a class="dropdown-item" href="{% url 'test_app:news03' %}">{{ news02.title }}</a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="{% url 'test_app:news_list' %}" style="background-color: #32393f; color: white;">все новости{% if user.is_superuser %}, удалить новость {% endif %}</a></li>
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link" href="{% url 'test_app:contact_us' %}">КОНТАКТЫ</a></li>

                {% if user.is_superuser %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">администрация</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                        <li><a class="dropdown-item" href="{% url 'test_app:create_news' %}">Добавить новость</a></li>
                        <li><a class="dropdown-item" href="{% url 'test_app:create_feedback' %}">Добавить отзыв</a></li>
                        <li><a class="dropdown-item" href="{% url 'test_app:photos' %}">Изменить карусель</a></li>
                    </ul>
                </li>
                {% endif %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdownPortfolio" href="" role="button" data-bs-toggle="dropdown" aria-expanded="false">Войти</a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownPortfolio">
                        <li><a class="dropdown-item" href="{% url 'userapp:login' %}">войти</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'userapp:logout' %}">выйти</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'userapp:registration' %}">зарегистрироваться</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item"><a class="nav-link" href="">{{user.username}}</a></li>
            </ul>
        </div>
    </div>
</nav>
<br>
<br>